//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _LTWeb08_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoaiTin
    {
        public TheLoaiTin()
        {
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public int IDLoai { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}
