//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _LTWeb08_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int IDTin { get; set; }
        public int IDLoai { get; set; }
        public string Tieudetin { get; set; }
        public string Noidungtin { get; set; }
    
        public virtual TheLoaiTin TheLoaiTin { get; set; }
    }
}
